version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: trading-db
    environment:
      POSTGRES_DB: trading_simulator
      POSTGRES_USER: trader
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - trading-network
      

  # pgAdmin (Database Management Tool)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: trading-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@trading.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - trading-network

  # Spring Boot Backend
  backend:
    build: ./backend
    container_name: trading-backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/trading_simulator
      - SPRING_DATASOURCE_USERNAME=trader
      - SPRING_DATASOURCE_PASSWORD=password123
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
    ports:
      - "8090:8090"
    depends_on:
      - postgres
    networks:
      - trading-network

  # React Frontend
  frontend:
    build: ./frontend
    container_name: trading-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - trading-network

volumes:
  postgres_data:

networks:
  trading-network:
    driver: bridge